name: Frinx common use-case wfs
description: Report a bug or unexpected behavior
labels: [bug, pending]

body:
  - type: markdown
    attributes:
      value:  Thank you for contributing to repository!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.

        Please provide as much detail as possible to make understanding and solving your problem as quick as possible.
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.

      placeholder: |
        import frinx

        ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, Poetry & Packages Version
      description: |
        Which versions of packages you are using?

        Please run the following command (or equivalent) and copy the output below:

        ```bash
        poetry env info
        poetry show
        poetry self --version
        ```

      render: Text
    validations:
      required: true
